### PR TITLE
Add image descriptions

### PR DESCRIPTION
**Pull request by towerofnix**
Also some minor whitespace tweaks.

Image descriptions are useful for anyone reading the page with a screen reader, or on a medium which doesn't support images (e.g. the terminal). Some of the scripts aren't exactly transcribed into a very audio-friendly way, but it's difficult to do so while not simply summarizing the script (which takes away the chance for a reader to intuit what a script does and learn how it works).

### CODE REVIEW

**Comment by brianharvey** [comment]
In BJC we indeed put the entire text of the script into the alt text.  It's a pain in the posterior, but has to be done.

**Comment by towerofnix** [comment]
Yup.. out of curiosity's sake what sort of syntax does that look like? Mine here works fine for relatively small scripts, but for the extremely big ones like the object/method example, I don't think it'd work quite so well!

If only Markdown let you have multi-line alt texts. I know it's something that HTML supports!

**Comment by brianharvey** [comment]
Here's a picture:
two-color-sierpinski-code
and here's its alt text:
alt="repeat (3) {set pen color to (red); move (100) steps; repeat (3) {set pen color to (blue); move (100) steps; turn clockwise (120) degrees}; turn right (120) degrees}"
We really don't have very long scripts in the curriculum, and even so it's not very consistent; as I look at it, one block says "turn clockwise" and another says "turn right."

**Comment by towerofnix** [comment]
I see, neat. It works for covering the whole script though. :)

**Pull request merged**
